version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        patterns: 
          - "*"
      security:
        patterns:
          - ".*"
        labels:
          - "security"
    labels:
      - "dependencies"
      - "auto-merge"
      - "npm"
    reviewers:
      - "krullmizter"
    security-updates: true

auto-merge:
  - match:
      dependency_type: "all"
      update_type: "semver:minor"
