name: Auto Merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Merge PR
        if: ${{ github.actor == 'dependabot[bot]' }}
        uses: actions/github-script@v4
        with:
          script: |
            const core = require('@actions/core');
            const { github, context } = require('@actions/github');
            
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

            try {
              const { data: pullRequest } = await octokit.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
              });

              if (pullRequest.mergeable && pullRequest.mergeable_state === "clean") {
                await octokit.rest.pulls.merge({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.payload.pull_request.number,
                  merge_method: "squash",
                });
                console.log("PR merged successfully.");
              } else {
                core.setFailed("PR is not mergeable.");
              }
            } catch (error) {
              core.setFailed(`Error during merge: ${error.message}`);
            }
