name: Auto Merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Merge PR
        uses: actions/github-script@v4
        with:
          script: |
            const { github, context } = require('@actions/github');

            const pullRequest = context.payload.pull_request;

            if (!pullRequest) {
              core.setFailed("No pull request context found.");
              return;
            }

            const mergeable = pullRequest.mergeable;
            const mergeableState = pullRequest.mergeable_state;

            if (mergeable && mergeableState === "clean") {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pullRequest.number,
                merge_method: "squash",
              });
              console.log("PR merged successfully.");
            } else {
              core.setFailed("PR is not mergeable.");
            }
